apiVersion: v1
kind: Pod
metadata:
  name: ambassador-example
spec:
  containers:
    - name: twemproxy
      image: ganomede/twemproxy
      command: ["nutcracker -c /etc/config/nutcracker.yaml -v 7 6222"]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: twem-config